[2014-03-13 07:30:10] log.ERROR: exception 'ErrorException' with message 'file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known' in /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php:483 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_get_conten...', '/media/gedi/pro...', 483, Array) #1 /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php(483): file_get_contents('https://github....') #2 /media/gedi/projects/thedevs.org/thedevs.org/app/routes.php(53): All::getGitStats(Object(User)) #3 [internal function]: {closure}('1') #4 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #5 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #6 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #7 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #8 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #9 /media/gedi/projects/thedevs.org/thedevs.org/public/index.php(53): Illuminate\Foundation\Application->run() #10 {main} [] []
[2014-03-13 07:30:27] log.ERROR: exception 'ErrorException' with message 'file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known' in /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php:483 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_get_conten...', '/media/gedi/pro...', 483, Array) #1 /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php(483): file_get_contents('https://github....') #2 /media/gedi/projects/thedevs.org/thedevs.org/app/routes.php(53): All::getGitStats(Object(User)) #3 [internal function]: {closure}('1') #4 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #5 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #6 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #7 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #8 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #9 /media/gedi/projects/thedevs.org/thedevs.org/public/index.php(53): Illuminate\Foundation\Application->run() #10 {main} [] []
[2014-03-13 09:59:22] log.ERROR: exception 'ErrorException' with message 'file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known' in /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php:483 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_get_conten...', '/media/gedi/pro...', 483, Array) #1 /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php(483): file_get_contents('https://github....') #2 /media/gedi/projects/thedevs.org/thedevs.org/app/routes.php(53): All::getGitStats(Object(User)) #3 [internal function]: {closure}('43') #4 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #5 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #6 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #7 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #8 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #9 /media/gedi/projects/thedevs.org/thedevs.org/public/index.php(53): Illuminate\Foundation\Application->run() #10 {main} [] []
[2014-03-13 09:59:48] log.ERROR: exception 'ErrorException' with message 'file_get_contents(): Filename cannot be empty' in /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php:483 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_get_conten...', '/media/gedi/pro...', 483, Array) #1 /media/gedi/projects/thedevs.org/thedevs.org/app/models/All.php(483): file_get_contents('') #2 /media/gedi/projects/thedevs.org/thedevs.org/app/routes.php(53): All::getGitStats(Object(User)) #3 [internal function]: {closure}('42') #4 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #5 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #6 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #7 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #8 /media/gedi/projects/thedevs.org/thedevs.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #9 /media/gedi/projects/thedevs.org/thedevs.org/public/index.php(53): Illuminate\Foundation\Application->run() #10 {main} [] []
